#!/bin/sh

killall -9 nomad
killall sleep

rm -rf /tmp/nomad-agent /tmp/plugin*

set -x

nomad agent -config agent.hcl > /tmp/nomad-dev.log 2>&1 &
sleep 12

nomad job run exec.hcl
nomad job run raw_exec.hcl
nomad job run docker.hcl

sleep 4

nomad job status exec.hcl
nomad job status raw_exec.hcl
nomad job status docker.hcl

echo "now run as root" 1>&2
