#!/bin/sh

i=1
for port in 7646 7647 7648; do
    name=client$i
    cat <<EOF > $name.hcl
log_level = "DEBUG"
data_dir = "/tmp/$name"
name = "$name"
enable_debug = true
client {
  enabled = true
  server_join {
    retry_join = ["127.0.0.1:4646"]
  }
}

plugin "raw_exec" {
  config {
    enabled = true
  }
}

ports {
  http = $port
}
EOF
    i=$((i + 1))
done


killall nomad
nomad agent -dev >/tmp/server.log 2>&1 &
for c in client*; do
    nomad agent -config $c >/tmp/${c%.hcl}.log 2>&1 &
done

sleep 6
nomad job run example.nomad
