#!/bin/sh
PATH="/usr/local/bin:$PATH"
set -x
export VAULT_ADDR='http://127.0.0.1:8200'
vault -version
vault policy write nomad-server nomad-server-policy.hcl
vault write /auth/token/roles/nomad-cluster @nomad-cluster-role.json
vault token create -policy nomad-server -period 72h -orphan


nomad agent -dev > /tmp/dev.log 2>&1 &