#!/bin/sh
set -x
[ -z "$1" ] && {
    echo "usage: $0 n"
    echo "       n: client number"
    exit 1
}

pid=`pgrep -fn "nomad.*client$1.hcl"`;
line=`sudo lsof -i TCP:4647 |grep "nomad *$pid "`;
ports=`echo "$line"|grep -oP '(?<=:)\d+(?=->)'`

echo "$ports"|while read port; do
    sudo iptables -A INPUT -p tcp --sport "$port" -j DROP
done
