#!/bin/sh
set -x
dir=/tmp/nomad-heartyeet
ppid=`cat $dir/server1/pid`

if [ -n "$ppid" ]; then
    gpid=`ps -o %r "$ppid"|tail -n1|awk '{print $1}'`
    sudo kill -TERM "-$gpid"
    sudo mv $dir $dir-`uuidgen`
fi

./depro
sleep 2

sudo pkill nomad
sudo pkill sleep
