#!/bin/sh
kill-nomad
cd ~/code/jobs
killall sleep
run-nomad clients
# run-nomad cluster
sleep 10
nomad job run raw.nomad

function await_job () {
    while [ `nomad job status raw.nomad|grep -c running` -lt 2 ]; do
	sleep 1
    done
}    

await_job()
# just kill, leave the state intact
killall nomad
run-nomad clients
await_job()

nomad job stop raw.nomad

# leaking isn't really a part of this bug
if [ `ps ax|grep -c "sleep 3000000"` -gt 1 ]; then
    echo tasks leaking
fi
