#!/bin/sh
set -ex

for x in server*; do
    nomad agent -server -config="$x" > /tmp/nomad-$$-"${x%hcl}log" 2>&1 &
done

for x in client*; do
    nomad agent -client -config="$x" > /tmp/nomad-$$-"${x%hcl}log" 2>&1 &
done
