#!/bin/sh

[ `id -u` = 0 ] || { echo "run as root" 1>&2; exit 1; }

killall -9 nomad
killall sleep

rm -rf /tmp/nomad-agent /tmp/plugin* 

set -x

(cd ~/go/src/github.com/hashicorp/nomad && go install)

nomad agent -config agent.json > /tmp/nomad-dev.log 2>&1 &
sleep 12

for i in `seq 1`; do
    nomad job run report.hcl
done
