#!/bin/sh
set -e
dir=/tmp/nomad-csi
nomad="$GOPATH"/bin/nomad

which csc >/dev/null || \
    GO111MODULE=off go get -u github.com/rexray/gocsi/csc

for a in server1 client1; do
    mkdir -p $dir/$a
    sudo $nomad agent -config $a.hcl > $dir/$a/log 2>&1 &
    echo $! > $dir/$a/pid
done

sleep 15

$nomad run plug.hcl || true
sleep 10
