#!/bin/sh
set -e
dir=/tmp/nomad-csi
CSI_ENDPOINT="$dir/client1/client/csi/monolith/plug/csi.sock"
nomad="$GOPATH"/bin/nomad

vid=`sudo csc --endpoint $CSI_ENDPOINT controller create-volume test-volume --cap 1,2,ext4|awk '{print $1}'|sed 's/"//g'`

sed "s/<VOLUME_ID>/$vid/g" vol.hcl > v.hcl
sed "s/<VOLUME_ID>/$vid/g" use.hcl > u.hcl

sleep 10

$nomad volume register v.hcl || true
$nomad run u.hcl
