#!/bin/sh
set -x
dir=/tmp/nomad-allocfs
nomad=${nomad:-`which nomad`}
export NOMAD_ADDR=http://127.0.0.1:4646

for a in server1 client1; do
    if pgrep -F "$dir/$a/pid" >/dev/null 2>&1; then
	continue
    fi

    mkdir -p $dir/$a
    sudo $nomad agent -config $a.hcl > $dir/$a/log 2>&1 &
    echo $! > $dir/$a/pid
done

sleep 1
$nomad run j.nomad

while [ `$nomad job status j|sed '0,/Allocations/d'|grep -c 'running'` = 0 ]; do
    sleep 1
done
